
language: python

python:
  - { PATH: "{{Python37}}", VERSION: 3.7, DIST: std, PYINT: python3.7, PYTHONPATH: src }
  - { PATH: "{{Python37}}", VERSION: 3.8, DIST: std, PYINT: python3.8, PYTHONPATH: src }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("$NAME_JENKINS", project_name + "_$VERSION_$DIST_$NAME"), "_venv")}}
  
install:
  - $PYINT -m pip install --upgrade pip
  - $PYINT -m pip install --upgrade --no-cache-dir --no-deps --index http://localhost:8067/simple/ pyquickhelper pyensae pymmails pymyinstall pyrsslocal mlstatpy ensae_teaching_cs jyquickhelper scikit-learn --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install -r requirements_conda.txt
  - $PYINT -m pip install -r requirements.txt
  - $PYINT -m pip install "shapely!=1.7.0,!=1.7.1"
  - $PYINT --version
  - $PYINT -m pip freeze

script:
  - { CMD: "$PYINT -u setup.py unittests", NAME: "UT", TIMEOUT: 3600 }
  - { CMD: "$PYINT -u setup.py unittests -e .*LONG.* -g .*LONG_LONG.* ", NAME: "UT_LONG", TIMEOUT: 5000 }  # gerry mandering
  - { CMD: "$PYINT -u setup.py unittests_SKIP", NAME: "UT_SKIP", TIMEOUT: 5000 }  # blaze
  - { CMD: "$PYINT -u setup.py unittests -e .*LONG_LONG.*", NAME: "UT_LONG_LONG", TIMEOUT: 5000 }  # gerry mandering in a notebook

after_script:
  - $PYINT -u setup.py bdist_wheel
  - if [ ${VERSION} == "3.7" and ${DIST} != "conda" and ${NAME} == "UT" ] then cp dist/*.whl {{root_path}}/../local_pypi/local_pypi_server fi

documentation:
  - if [ ${NAME} == "UT" ] then $PYINT -u setup.py build_sphinx fi
  - if [ ${NAME} == "UT" ] then cp -R -f _doc/sphinxdoc/build/html dist/html fi
